global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'neontask-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'neontask-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /health
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
