apiVersion: v1
kind: Namespace
metadata:
  name: neontask
  labels:
    app: neontask
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: neontask-quota
  namespace: neontask
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
    services: "5"
