apiVersion: v1
kind: Secret
metadata:
  name: neontask-secrets
  namespace: neontask
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  database-password: cGFzc3dvcmQxMjM= # password123
  jwt-secret: c3VwZXJzZWNyZXRqd3RrZXk= # supersecretjwtkey
  api-key: YXBpa2V5MTIzNDU= # apikey12345
---
apiVersion: v1
kind: Secret
metadata:
  name: neontask-registry-secret
  namespace: neontask
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
